pandas: Autospec creation for update from version 1.5.0 to version 1.5.1
Marco Edward Gorelli (1):
      Backport PR #49053 on branch 1.5.x (REVERT caching in find_stack_level) (#49079)

MeeseeksMachine (42):
      Backport PR #48642 on branch 1.5.x (DOC: Add release notes for 1.5.1) (#48647)
      Backport PR #48639 on branch 1.5.x (CI: Fix directory name for published prod docs) (#48648)
      Backport PR #48651 on branch 1.5.x (REGR: TextIOWrapper raising an error in read_csv) (#48666)
      Backport PR #48599 on branch 1.5.x (DOC: Add deprecation infos to deprecated functions) (#48690)
      Backport PR #48620 on branch 1.5.x (REGR: Performance decrease in factorize) (#48710)
      Backport PR #48711 on branch 1.5.x (REGR: Regression in DataFrame.loc when setting df with all True indexer) (#48717)
      Backport PR #48696 on branch 1.5.x (REGR: to_hdf raising AssertionError with boolean index) (#48716)
      Backport PR #48734 on branch 1.5.x (REGR: Raise on invalid colormap for scatter plot) (#48744)
      Backport PR #48713 on branch 1.5.x (BUG: pivot_table raising Future Warning with datetime column as index) (#48742)
      Backport PR #48703 on branch 1.5.x (Added theme_switcher ) (#48741)
      Backport PR #48697 on branch 1.5.x (REGR: None converted to NaN when enlarging Series) (#48745)
      Backport PR #48702 on branch 1.5.x (REGR: dropna affects observed in groupby) (#48750)
      Backport PR #48782 on branch 1.5.x (REGR: describe raising when result contains NA) (#48793)
      Backport PR #48662 on branch 1.5.x (BUG: Series.getitem not falling back to positional for bool index) (#48799)
      Backport PR #48751 on branch 1.5.x (WEB: Update link to datapythonista blog url) (#48798)
      Backport PR #48608 on branch 1.5.x (REGR: assert_index_equal raising with non matching pd.NA) (#48800)
      Backport PR #48785 on branch 1.5.x (BUG: still emitting unnecessary FutureWarning in DataFrame.sort_values with sparse columns) (#48807)
      Backport PR #48693 on branch 1.5.x (ENH: Make deprecate_nonkeyword_arguments alter function signature) (#48795)
      Backport PR #48790 on branch 1.5.x (Created icons for dark theme) (#48875)
      Backport PR #48805 on branch 1.5.x (Added padding and fixed columns for sponsor logos in mobile view) (#48874)
      Backport PR #48866 on branch 1.5.x (REGR: replace replacing wrong values with inplace and datetime) (#48872)
      Backport PR #48853 on branch 1.5.x (REGR: Avoid unnecessary warning when setting empty dataframe) (#48873)
      Backport PR #48833 on branch 1.5.x (BUG: ArrowExtensionArray compared to invalid object not raising) (#48878)
      Backport PR #48686 on branch 1.5.x (BUG: to_datetime(tz_mix, utc=True) converts to UTC) (#48882)
      Backport PR #48879 on branch 1.5.x (WEB: Add Luke to maintainers list) (#48929)
      Backport PR #48824 on branch 1.5.x (REGR: groupby fails with nullable dtypes and dropna=False) (#48938)
      Backport PR #48935 on branch 1.5.x (DOC: reverted directive for SAS logo white) (#48960)
      Backport PR #48943 on branch 1.5.x (REGR: ExcelWriter.book not settable) (#48959)
      Backport PR #48989 on branch 1.5.x (CI: Pin pydata sphinx theme) (#48993)
      Backport PR #48412 on branch 1.5.x (BUG: safe_sort losing MultiIndex dtypes) (#49002)
      Backport PR #48973 on branch 1.5.x (CI: Bump timeouts Python dev builds) (#49028)
      Backport PR #48987 on branch 1.5.x (REG: Fix regression in assert_frame_equal for categorical and check_like) (#48997)
      Backport PR #48990 on branch 1.5.x (DOC: replace developer meeting with contributor community page) (#49067)
      Backport PR #48995 on branch 1.5.x (REGR: to_parquet raising with bytes filename) (#49061)
      Backport PR #49070 on branch 1.5.x (CI: Fix DeprecationWarning of numpy dev) (#49074)
      Backport PR #49072 on branch 1.5.x (BUG: redirect from meeting to community was incorrect) (#49077)
      Backport PR #48457 on branch 1.5.x (TST: Fix unsigned pyarrow types in SIGNED_INT_PYARROW_DTYPES) (#49093)
      Backport PR #49080 on branch 1.5.x (REGR: midx.values resetting freq of underyling index) (#49094)
      Backport PR #48770 on branch 1.5.x (added sytle in stylesheet for <blockquote>) (#49102)
      Backport PR #49137 on branch 1.5.x (WEB/DOC: Fix typo in OVH name) (#49138)
      Backport PR #49140 on branch 1.5.x (Revert "PERF: faster corrwith method for pearson and spearman correlation when other is a Series and axis = 0 (column-wise) (#46174)") (#49151)
      Backport PR #49162 on branch 1.5.x (PERF: Fix performance regression for isin with mismatching dtypes) (#49165)

Pandas Development Team (1):
      RLS: 1.5.1

Patrick Hoefler (4):
      Backport PR #48820 on branch 1.5.x (BUG: to_datetime(format='...%f') parses nanoseconds) (#48860)
      Backport PR #48850 on branch 1.5.x (TYP: Fix typing errors caused by new numpy) (#48859)
      Backport PR #48736 on branch 1.5.x ( BUG: AttributeError: 'function' object has no attribute 'currentframe') (#48887)
      Backport PR #48797 on branch 1.5.x (REGR: fix df.apply with keyword non-zero axis) (#48886)

Richard Shadrach (2):
      Backport PR #48579 on branch 1.5.x (BUG: Fix calling groupBy(...).apply(func) on an empty dataframe invokes func) (#48817)
      Backport PR #48760 on branch 1.5.x (REGR: groupby.size with axis=1 doesn't return a Series) (#48825)